[package]
name = "mitm-ag-tauri"
version = "0.2.4"
description = "MITM AG native desktop shell"
authors = ["MITM Antigravity"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "=2.5.6", features = [] }

[dependencies]
tauri                = { version = "=2.10.1", features = [] }
tauri-plugin-updater = { version = "2" }
serde_json           = "1"
